
POST https://localhost/api/v1/users HTTP/1.1
content-type: application/json
accept: application/json

{
    "email": "barx@mail.ch",
    "firstname": "Billx",
    "lastname": "Barx",
    "password": "passwordx",
    "role": "ROLE_FOO_BAR",
    "organisation": "Barx Organisation"
}