services:
  nginx:
    container_name: pff-api-dev-nginx
    restart: always
    build: 
      context: ./.docker/nginx
      target: dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/certbot/conf/:/etc/nginx/ssl/:ro
      #- ./.docker/certbot/www/:/var/www/certbot/:ro
      #- ./.docker/nginx/ssl/:/etc/nginx/ssl/:ro      

    depends_on:
      - php-fpm

  php-fpm:
    container_name: pff-api-dev-php
    build: ./.docker/php-fpm
    environment:
      - DOCKER=1
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_PASSWORD=${DB_PASSWORD}

    volumes:
      - ./app:/var/www/html
    links:
      - postgres
  
  certbot:
    container_name: pff-api-dev-certbot
    image: certbot/certbot:latest
    volumes:
      #- ./.docker/certbot/www/:/var/www/certbot/:rw
      - ./.docker/certbot/conf/:/etc/letsencrypt/:rw

  postgres:
    container_name: pff-api-dev-postgres
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: pff-api-dev-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: