@customer_id = 8

### 
PUT https://localhost/api/customers/{{customer_id}} HTTP/1.1
content-type: application/json
accept: application/json

{
    "name": "Baz",
    "email": "new2@baz.com",
    "organisation": "Baz Organisation 1"    
}