@customer_id = 2

### 
PUT https://localhost/api/v1/customers/{{customer_id}} HTTP/1.1
content-type: application/json
accept: application/json

{
    "email": "barxupdated@mail.ch",
    "firstname": "BillX",
    "lastname": "BarX",
    "password": "passwordX",
    "organisation": "BarX Organisation"
}