
POST https://localhost/api/folders HTTP/1.1
content-type: application/json
accept: application/json

{
    "id_customer": "2",
    "title": "study 2.2 bar",
    "description": "2nd study of customer 2 bar"
}